#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Insert the most basic emergency numbers for each country in the directory tree
# as individual json files emergency.json.
#

import csv
import os

codes = {'Afghanistan':'AF',
    'Åland Islands':'AX',
    'Albania':'AL',
    'Algeria':'DZ',
    'American Samoa':'AS',
    'Andorra':'AD',
    'Angola':'AO',
    'Anguilla':'AI',
    'Antarctica':'AQ',
    'Antigua and Barbuda':'AG',
    'Argentina':'AR',
    'Armenia':'AM',
    'Aruba':'AW',
    'Australia':'AU',
    'Austria':'AT',
    'Azerbaijan':'AZ',
    'Bahamas':'BS',
    'Bahrain':'BH',
    'Bangladesh':'BD',
    'Barbados':'BB',
    'Belarus':'BY',
    'Belgium':'BE',
    'Belize':'BZ',
    'Benin':'BJ',
    'Bermuda':'BM',
    'Bhutan':'BT',
    'Bolivia':'BO',
    'Bonaire, Sint Eustatius and Saba':'BQ',
    'Bosnia and Herzegovina':'BA',
    'Botswana':'BW',
    'Bouvet Island':'BV',
    'Brazil':'BR',
    'British Indian Ocean Territory':'IO',
    'Brunei Darussalam':'BN',
    'Bulgaria':'BG',
    'Burkina Faso':'BF',
    'Burundi':'BI',
    'Cambodia':'KH',
    'Cameroon':'CM',
    'Canada':'CA',
    'Cape Verde':'CV',
    'Cayman Islands':'KY',
    'Central African Republic':'CF',
    'Chad':'TD',
    'Chile':'CL',
    'China':'CN',
    'Christmas Island':'CX',
    'Cocos  Islands':'CC',
    'Colombia':'CO',
    'Comoros':'KM',
    'Congo':'CG',
    'Congo, The Democratic Republic Of The':'CD',
    'Cook Islands':'CK',
    'Costa Rica':'CR',
    'Côte D\'Ivoire':'CI',
    'Croatia':'HR',
    'Cuba':'CU',
    'Curaçao':'CW',
    'Cyprus':'CY',
    'Czech Republic':'CZ',
    'Denmark':'DK',
    'Djibouti':'DJ',
    'Dominica':'DM',
    'Dominican Republic':'DO',
    'Ecuador':'EC',
    'Egypt':'EG',
    'El Salvador':'SV',
    'Equatorial Guinea':'GQ',
    'Eritrea':'ER',
    'Estonia':'EE',
    'Ethiopia':'ET',
    'Falkland Islands':'FK',
    'Faroe Islands':'FO',
    'Fiji':'FJ',
    'Finland':'FI',
    'France':'FR',
    'French Guiana':'GF',
    'French Polynesia':'PF',
    'French Southern Territories':'TF',
    'Gabon':'GA',
    'Gambia':'GM',
    'Georgia':'GE',
    'Germany':'DE',
    'Ghana':'GH',
    'Gibraltar':'GI',
    'Greece':'GR',
    'Greenland':'GL',
    'Grenada':'GD',
    'Guadeloupe':'GP',
    'Guam':'GU',
    'Guatemala':'GT',
    'Guernsey':'GG',
    'Guinea-Bissau':'GW',
    'Guinea':'GN',
    'Guyana':'GY',
    'Haiti':'HT',
    'Heard &amp; McDonald Islands':'HM',
    'Honduras':'HN',
    'Hong Kong':'HK',
    'Hungary':'HU',
    'Iceland':'IS',
    'India':'IN',
    'Indonesia':'ID',
    'Iran':'IR',
    'Iraq':'IQ',
    'Ireland':'IE',
    'Isle of Man':'IM',
    'Israel':'IL',
    'Italy':'IT',
    'Jamaica':'JM',
    'Japan':'JP',
    'Jersey':'JE',
    'Jordan':'JO',
    'Kazakhstan':'KZ',
    'Kenya':'KE',
    'Kiribati':'KI',
    'Korea, Democratic People\'s Republic Of':'KP',
    'Korea, Republic of':'KR',
    'Kuwait':'KW',
    'Kyrgyzstan':'KG',
    'Laos':'LA',
    'Latvia':'LV',
    'Lebanon':'LB',
    'Lesotho':'LS',
    'Liberia':'LR',
    'Libya':'LY',
    'Liechtenstein':'LI',
    'Lithuania':'LT',
    'Luxembourg':'LU',
    'Macau':'MO',
    'Macedonia, the Former Yugoslav Republic Of':'MK',
    'Madagascar':'MG',
    'Malawi':'MW',
    'Malaysia':'MY',
    'Maldives':'MV',
    'Mali':'ML',
    'Malta':'MT',
    'Marshall Islands':'MH',
    'Martinique':'MQ',
    'Mauritania':'MR',
    'Mauritius':'MU',
    'Mayotte':'YT',
    'Mexico':'MX',
    'Micronesia, Federated States Of':'FM',
    'Moldova':'MD',
    'Monaco':'MC',
    'Mongolia':'MN',
    'Montenegro':'ME',
    'Montserrat':'MS',
    'Morocco':'MA',
    'Mozambique':'MZ',
    'Myanmar':'MM',
    'Namibia':'NA',
    'Nauru':'NR',
    'Nepal':'NP',
    'Netherlands':'NL',
    'New Caledonia':'NC',
    'New Zealand':'NZ',
    'Nicaragua':'NI',
    'Nigeria':'NG',
    'Niger':'NE',
    'Niue':'NU',
    'Norfolk Island':'NF',
    'Northern Mariana Islands':'MP',
    'Norway':'NO',
    'Oman':'OM',
    'Pakistan':'PK',
    'Palau':'PW',
    'Palestine':'PS',
    'Panama':'PA',
    'Papua New Guinea':'PG',
    'Paraguay':'PY',
    'Peru':'PE',
    'Philippines':'PH',
    'Pitcairn':'PN',
    'Poland':'PL',
    'Portugal':'PT',
    'Puerto Rico':'PR',
    'Qatar':'QA',
    'Reunion':'RE',
    'Romania':'RO',
    'Russia':'RU',
    'Rwanda':'RW',
    'Saint Helena, Ascension and Tristan Da Cunha':'SH',
    'Saint Kitts And Nevis':'KN',
    'Saint Lucia':'LC',
    'Saint Vincent And The Grenadines':'VC',
    'Samoa':'WS',
    'San Marino':'SM',
    'Sao Tome and Principe':'ST',
    'Saudi Arabia':'SA',
    'Senegal':'SN',
    'Serbia':'RS',
    'Seychelles':'SC',
    'S.Georgia &amp; S.Sandwich Islands':'GS',
    'Sierra Leone':'SL',
    'Singapore':'SG',
    'Slovakia':'SK',
    'Slovenia':'SI',
    'Solomon Islands':'SB',
    'Somalia':'SO',
    'South Africa':'ZA',
    'South Sudan':'SS',
    'Spain':'ES',
    'Sri Lanka':'LK',
    'St. Barthélemy':'BL',
    'St. Maarten':'SX',
    'St. Martin':'MF',
    'St. Pierre &amp; Miquelon':'PM',
    'Sudan':'SD',
    'Suriname':'SR',
    'Svalbard &amp; Jan Mayen Islands':'SJ',
    'Swaziland':'SZ',
    'Sweden':'SE',
    'Switzerland':'CH',
    'Syria':'SY',
    'Taiwan':'TW',
    'Tajikistan':'TJ',
    'Tanzania':'TZ',
    'Thailand':'TH',
    'East Timor':'TL',
    'Togo':'TG',
    'Tokelau':'TK',
    'Tonga':'TO',
    'Trinidad and Tobago':'TT',
    'Tunisia':'TN',
    'Turkey':'TR',
    'Turkmenistan':'TM',
    'Turks &amp; Caicos Islands':'TC',
    'Tuvalu':'TV',
    'Uganda':'UG',
    'Ukraine':'UA',
    'United Arab Emirates':'AE',
    'United Kingdom':'GB',
    'United States Minor Outlying Islands':'UM',
    'United States':'US',
    'Uruguay':'UY',
    'Uzbekistan':'UZ',
    'Vanuatu':'VU',
    'Vatican City':'VA',
    'Venezuela':'VE',
    'Viet Nam':'VN',
    'Virgin Islands':'VG',
    'Virgin Islands':'VI',
    'Wallis &amp; Futuna Islands':'WF',
    'Western Sahara':'EH',
    'Yemen':'YE',
    'Zambia':'ZM',
    'Zimbabwe':'ZW'}

with open('emergency-numbers.csv') as f:
    c = csv.reader(f)
    for row in c:
        country = row[0]
        if country in codes:
            code = codes[country]
            numPolice = row[1]
            numAmbulance = row[2]
            numFire = row[3]
            
            json = "{ \"emergency\": {\n\
    \"ambulance\": {\n\
        \"phone\": \"" + numAmbulance + "\"\n\
     },\n\
     \"fire\": {\n\
         \"phone\": \"" + numFire + "\"\n\
     },\n\
     \"police\": {\n\
        \"phone\": \"" + numPolice + "\"\n\
     }\n\
}}\n"
#            print country + '/' + code + " police " + numPolice
            outFile = open('../data/' + code + '/emergency.json', 'w')
            outFile.write(json)
            outFile.close()

        else:
            print "********************* didn't recognice '" + country + "'"
    f.close()

